#ifndef VDQUEUE_CONFIG_HH
#define VDQUEUE_CONFIG_HH

#include <cstdint>
#include <string>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <map>

namespace cellular_emulation {

/**
 * @struct VDQueueConfig
 * @brief Configuration parameters for Virtual Driver Queue
 * 
 * These parameters can be tuned to match the buffering characteristics
 * of different cellular modems and network drivers.
 */
struct VDQueueConfig {
    /**
     * @brief Maximum number of packets the driver queue can hold
     * 
     * This corresponds to the kernel's network driver transmit queue length.
     * Typical values range from 64 to 256 packets.
     * Default: 128 packets (based on common Qualcomm modem driver settings)
     */
    size_t max_queue_size = 128;

    /**
     * @brief Maximum total bytes the queue can hold (0 = unlimited)
     * 
     * Some drivers limit queue size by bytes rather than packets.
     * Set to 0 to disable byte-based limiting.
     * Default: 0 (packet-based limiting only)
     */
    size_t max_queue_bytes = 0;

    /**
     * @brief Maximum packet size (MTU)
     * 
     * Packets larger than this will be dropped.
     * Default: 1504 bytes (standard TUN MTU)
     */
    size_t max_packet_size = 1504;

    /**
     * @brief Enable detailed logging
     * Default: false
     */
    bool enable_logging = false;

    /**
     * @brief Log file path (if logging enabled)
     * Default: empty (use stdout)
     */
    std::string log_file_path = "";

    /**
     * @brief Minimum interval between signal exports (milliseconds)
     * 
     * To avoid excessive I/O overhead, signals are exported at most
     * once per this interval.
     * Default: 1 ms
     */
    uint64_t signal_export_interval_ms = 1;

    /**
     * @brief Path for signal export file
     * Default: /tmp/mm_virtual_driver_queue
     */
    std::string signal_export_path = "/tmp/mm_virtual_driver_queue";

    /**
     * @brief Enable per-packet timestamp tracking
     * 
     * Required for dwell time calculations. Disable for minimal overhead.
     * Default: true
     */
    bool track_timestamps = true;

    /**
     * @brief Enable statistics collection
     * Default: true
     */
    bool collect_statistics = true;

    /**
     * @brief Default constructor with default values
     */
    VDQueueConfig() = default;

    /**
     * @brief Construct from configuration file
     * @param config_path Path to configuration file
     */
    explicit VDQueueConfig(const std::string& config_path)
    {
        load_from_file(config_path);
    }

    /**
     * @brief Load configuration from file
     * @param config_path Path to configuration file
     * @throws std::runtime_error if file cannot be opened or parsed
     * 
     * File format (key=value pairs, one per line):
     *   max_queue_size=128
     *   max_packet_size=1504
     *   signal_export_path=/tmp/mm_vdqueue
     */
    void load_from_file(const std::string& config_path)
    {
        std::ifstream file(config_path);
        if (!file.is_open()) {
            throw std::runtime_error("Cannot open config file: " + config_path);
        }

        std::string line;
        int line_number = 0;
        
        while (std::getline(file, line)) {
            line_number++;
            
            /* Skip empty lines and comments */
            if (line.empty() || line[0] == '#') {
                continue;
            }

            /* Parse key=value */
            size_t eq_pos = line.find('=');
            if (eq_pos == std::string::npos) {
                throw std::runtime_error("Invalid config line " + 
                    std::to_string(line_number) + ": " + line);
            }

            std::string key = line.substr(0, eq_pos);
            std::string value = line.substr(eq_pos + 1);

            /* Trim whitespace */
            key.erase(0, key.find_first_not_of(" \t"));
            key.erase(key.find_last_not_of(" \t") + 1);
            value.erase(0, value.find_first_not_of(" \t"));
            value.erase(value.find_last_not_of(" \t") + 1);

            /* Set configuration value */
            set_value(key, value);
        }
    }

    /**
     * @brief Save configuration to file
     * @param config_path Path to output file
     */
    void save_to_file(const std::string& config_path) const
    {
        std::ofstream file(config_path);
        if (!file.is_open()) {
            throw std::runtime_error("Cannot open config file for writing: " + config_path);
        }

        file << "# Virtual Driver Queue Configuration\n";
        file << "# Generated by Mahimahi Cellular Emulation\n\n";

        file << "max_queue_size=" << max_queue_size << "\n";
        file << "max_queue_bytes=" << max_queue_bytes << "\n";
        file << "max_packet_size=" << max_packet_size << "\n";
        file << "enable_logging=" << (enable_logging ? "true" : "false") << "\n";
        file << "log_file_path=" << log_file_path << "\n";
        file << "signal_export_interval_ms=" << signal_export_interval_ms << "\n";
        file << "signal_export_path=" << signal_export_path << "\n";
        file << "track_timestamps=" << (track_timestamps ? "true" : "false") << "\n";
        file << "collect_statistics=" << (collect_statistics ? "true" : "false") << "\n";
    }

    /**
     * @brief Get string representation
     * @return String describing all configuration values
     */
    std::string to_string() const
    {
        std::ostringstream oss;
        oss << "VDQueueConfig{"
            << "max_queue_size=" << max_queue_size
            << ", max_queue_bytes=" << max_queue_bytes
            << ", max_packet_size=" << max_packet_size
            << ", signal_export_path=" << signal_export_path
            << "}";
        return oss.str();
    }

    /**
     * @brief Validate configuration values
     * @return true if all values are valid
     * @throws std::runtime_error with description of invalid value
     */
    bool validate() const
    {
        if (max_queue_size == 0) {
            throw std::runtime_error("max_queue_size must be > 0");
        }
        if (max_packet_size == 0) {
            throw std::runtime_error("max_packet_size must be > 0");
        }
        if (max_packet_size > 65535) {
            throw std::runtime_error("max_packet_size must be <= 65535");
        }
        return true;
    }

private:
    /**
     * @brief Set a configuration value by key
     * @param key Configuration key name
     * @param value Configuration value as string
     */
    void set_value(const std::string& key, const std::string& value)
    {
        if (key == "max_queue_size") {
            max_queue_size = std::stoull(value);
        } else if (key == "max_queue_bytes") {
            max_queue_bytes = std::stoull(value);
        } else if (key == "max_packet_size") {
            max_packet_size = std::stoull(value);
        } else if (key == "enable_logging") {
            enable_logging = (value == "true" || value == "1");
        } else if (key == "log_file_path") {
            log_file_path = value;
        } else if (key == "signal_export_interval_ms") {
            signal_export_interval_ms = std::stoull(value);
        } else if (key == "signal_export_path") {
            signal_export_path = value;
        } else if (key == "track_timestamps") {
            track_timestamps = (value == "true" || value == "1");
        } else if (key == "collect_statistics") {
            collect_statistics = (value == "true" || value == "1");
        }
        /* Unknown keys are silently ignored */
    }
};

/**
 * @brief Predefined configurations for common cellular modems
 */
namespace ModemProfiles {

/**
 * @brief Qualcomm SDX55 modem profile (commonly used in 5G devices)
 */
inline VDQueueConfig qualcomm_sdx55()
{
    VDQueueConfig config;
    config.max_queue_size = 128;
    config.max_packet_size = 1504;
    config.signal_export_interval_ms = 1;
    return config;
}

/**
 * @brief Intel XMM 7560 modem profile
 */
inline VDQueueConfig intel_xmm7560()
{
    VDQueueConfig config;
    config.max_queue_size = 64;
    config.max_packet_size = 1504;
    config.signal_export_interval_ms = 2;
    return config;
}

/**
 * @brief Samsung Exynos modem profile
 */
inline VDQueueConfig samsung_exynos()
{
    VDQueueConfig config;
    config.max_queue_size = 96;
    config.max_packet_size = 1504;
    config.signal_export_interval_ms = 1;
    return config;
}

/**
 * @brief Generic LTE modem profile (conservative settings)
 */
inline VDQueueConfig generic_lte()
{
    VDQueueConfig config;
    config.max_queue_size = 100;
    config.max_packet_size = 1500;
    config.signal_export_interval_ms = 2;
    return config;
}

/**
 * @brief High-throughput 5G modem profile
 */
inline VDQueueConfig high_throughput_5g()
{
    VDQueueConfig config;
    config.max_queue_size = 256;
    config.max_packet_size = 9000;  /* Jumbo frames */
    config.signal_export_interval_ms = 1;
    return config;
}

} // namespace ModemProfiles

} // namespace cellular_emulation

#endif /* VDQUEUE_CONFIG_HH */
